# 仅供参考，请根据服务器实际情况修改
version: '3.3'
services:
  qinglong:
    container_name: qinglong
    image: "whyour/qinglong:latest"
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - /volume1/docker/qinglong/qinglong/data:/ql/data
    privileged: true
    network_mode: host

  jdx:
    container_name: jdx
    build:
      context: /volume1/docker/qinglong/jdx
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - /volume1/docker/qinglong/jdx/config:/jdx/config
      - /volume1/docker/qinglong/jdx/logs:/jdx/logs
      # 挂载为青龙挂载到宿主机的数据库文件
      - /volume1/docker/qinglong/qinglong/data/db/bean-log.db:/bean-log.db
    privileged: true
    networks:
      qinglong:
        ipv4_address: 172.21.0.102

  jdx-nginx:
    container_name: jdx-nginx
    image: "nginx"
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - /volume1/docker/qinglong/jdx/nginx:/etc/nginx/conf.d
      - /volume1/docker/qinglong/jdx/dist:/html
    privileged: true
    networks:
      qinglong:
        ipv4_address: 172.21.0.103

networks:
  qinglong:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
