# ???????????
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=SQL: %(sql) \nExecution Time: %(executionTime)ms\n---
# ????????
appender=com.p6spy.engine.spy.appender.StdoutLogger

# ??? SQLite ??????????? p6spy ?????????
driverlist=org.sqlite.JDBC

# ???????? SQL??????
sqlFormat=true

# ??????????? SQL??????????
# exclude=PRAGMA table_info
