server {
    # 项目在容器内部运行的端口
    listen       6443;

    server_name  _;

    # 前端访问路径配置
    location / {
        root   /html;
        # 防止刷新404
        try_files $uri $uri/ /index.html;
        index  index.html index.htm;


        # 静态资源缓存
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$|^/(assets)/ {
            expires 120d;
            add_header Cache-Control "public";
        }

        # index.html 永不缓存
        location = /index.html {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
            expires -1;
        }
    }

    location /api/{
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header REMOTE-HOST $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://127.0.0.1:8090/;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}

proxy_connect_timeout 300000s;
proxy_read_timeout 300000s;
proxy_send_timeout 300000s;
